/**
 * HermesConsole.tsx — internal operator console.
 *
 * Operator-only. Renders a curated snapshot of local Hermes / Hearthlands
 * runtime state. The snapshot is generated by scripts/hermes_snapshot.py
 * and served at /hermes-snapshot.json.
 *
 * No arbitrary file browser. No destructive actions. No live process
 * spawning. The UI does not enumerate the local machine; it renders a
 * pre-collected typed JSON object.
 */
import { useEffect, useState } from 'react';
import {
  Activity,
  AlertCircle,
  Cpu,
  Database,
  FileText,
  RefreshCw,
} from 'lucide-react';

type LmStudio = {
  port: number;
  online: boolean;
  models: number | string | null;
  checked_at: string | null;
};

type ProcessRow =
  | { raw: string; _error?: undefined }
  | { _error: string; raw?: undefined };

type WorldState = Record<string, unknown> | null;

type Snapshot = {
  generated_at: string;
  lm_studio: LmStudio;
  hermes_processes: ProcessRow[];
  mempalace_stream: { tail: string; parse_status: string };
  hearth_world_state: WorldState;
  heartbeat_log_tail: string;
  solis_log_tail: string;
  soul_md_head: string;
  file_references: Array<{ label: string; path: string }>;
};

function fmtTime(iso: string): string {
  try {
    return new Date(iso).toLocaleString();
  } catch {
    return iso;
  }
}

function worldKey(state: WorldState, key: string): string {
  if (!state || typeof state !== 'object') return '—';
  const v = (state as Record<string, unknown>)[key];
  if (v === null || v === undefined) return '—';
  if (typeof v === 'object') return JSON.stringify(v);
  return String(v);
}

export default function HermesConsole() {
  const [snap, setSnap] = useState<Snapshot | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function load(): Promise<void> {
    setLoading(true);
    setError(null);
    try {
      const r = await fetch('/hermes-snapshot.json', { cache: 'no-store' });
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      const data = (await r.json()) as Snapshot;
      setSnap(data);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    void load();
    const t = window.setInterval(() => {
      void load();
    }, 30_000);
    return () => {
      window.clearInterval(t);
    };
  }, []);

  return (
    <div className="h-full overflow-y-auto bg-[#020804] text-gray-200 p-6 font-sans">
      <div className="max-w-6xl mx-auto">
        <header className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-2xl font-bold text-[#10b981] flex items-center gap-3">
              <Cpu size={28} /> Hermes Console
            </h1>
            <p className="text-xs text-gray-500 mt-1 font-mono">
              {snap
                ? `snapshot ${fmtTime(snap.generated_at)}`
                : 'no snapshot loaded'}
            </p>
          </div>
          <button
            onClick={() => void load()}
            disabled={loading}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-[#10b981]/15 border border-[#10b981]/30 text-[#10b981] hover:bg-[#10b981]/25 transition disabled:opacity-50"
          >
            <RefreshCw size={16} className={loading ? 'animate-spin' : ''} />
            Refresh
          </button>
        </header>

        {error && (
          <div className="mb-6 p-4 rounded-lg border border-[#ef4444]/40 bg-[#ef4444]/10 text-[#ef4444] text-sm flex items-start gap-3">
            <AlertCircle size={16} className="mt-0.5" />
            <div>
              <div>
                Could not load{' '}
                <code className="font-mono">hermes-snapshot.json</code>: {error}
              </div>
              <div className="text-xs mt-1 text-gray-400">
                Run{' '}
                <code className="font-mono">
                  python scripts/hermes_snapshot.py
                </code>{' '}
                from the repo root to generate it.
              </div>
            </div>
          </div>
        )}

        {snap && (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            <section className="glass-panel p-5 rounded-xl">
              <h2 className="text-sm font-bold uppercase tracking-widest text-gray-400 mb-4 flex items-center gap-2">
                <Activity size={14} /> Overview
              </h2>
              <dl className="text-sm space-y-2 font-mono">
                <div className="flex justify-between">
                  <dt className="text-gray-500">LM Studio</dt>
                  <dd
                    className={
                      snap.lm_studio.online ? 'text-[#10b981]' : 'text-[#ef4444]'
                    }
                  >
                    {snap.lm_studio.online
                      ? `Online · ${snap.lm_studio.models ?? '?'} models`
                      : 'Offline'}
                  </dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-gray-500">Hermes processes</dt>
                  <dd>{snap.hermes_processes.length} detected</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-gray-500">Last world tick</dt>
                  <dd>{worldKey(snap.hearth_world_state, 'tick')}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-gray-500">Last intent</dt>
                  <dd>{worldKey(snap.hearth_world_state, 'last_intent')}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-gray-500">Heat</dt>
                  <dd>{worldKey(snap.hearth_world_state, 'heat')}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-gray-500">Ember balance</dt>
                  <dd>{worldKey(snap.hearth_world_state, 'ember_balance')}</dd>
                </div>
              </dl>
            </section>

            <section className="glass-panel p-5 rounded-xl">
              <h2 className="text-sm font-bold uppercase tracking-widest text-gray-400 mb-4 flex items-center gap-2">
                <Cpu size={14} /> Processes
              </h2>
              <ul className="text-xs font-mono space-y-1 max-h-72 overflow-y-auto">
                {snap.hermes_processes.length === 0 && (
                  <li className="text-gray-500">
                    no hermes processes detected
                  </li>
                )}
                {snap.hermes_processes.map((p, i) => (
                  <li key={i} className="text-gray-300 break-all">
                    {p._error ? (
                      <span className="text-[#ef4444]">{p._error}</span>
                    ) : (
                      p.raw
                    )}
                  </li>
                ))}
              </ul>
            </section>

            <section className="glass-panel p-5 rounded-xl">
              <h2 className="text-sm font-bold uppercase tracking-widest text-gray-400 mb-4 flex items-center gap-2">
                <Database size={14} /> Memory
              </h2>
              <div className="text-xs font-mono space-y-3">
                <div>
                  <div className="text-gray-500 mb-1">mempalace tail</div>
                  <pre className="text-gray-300 bg-black/40 p-3 rounded overflow-x-auto whitespace-pre-wrap break-words max-h-40 overflow-y-auto">
                    {snap.mempalace_stream.tail || '(empty)'}
                  </pre>
                </div>
                <div>
                  <div className="text-gray-500 mb-1">
                    world state (key fields)
                  </div>
                  <pre className="text-gray-300 bg-black/40 p-3 rounded overflow-x-auto whitespace-pre-wrap break-words">
                    {JSON.stringify(
                      {
                        heat: (snap.hearth_world_state as Record<string, unknown>)
                          ?.heat,
                        ember_balance: (
                          snap.hearth_world_state as Record<string, unknown>
                        )?.ember_balance,
                        tick: (snap.hearth_world_state as Record<string, unknown>)
                          ?.tick,
                        last_intent: (
                          snap.hearth_world_state as Record<string, unknown>
                        )?.last_intent,
                        heartbeat_at: (
                          snap.hearth_world_state as Record<string, unknown>
                        )?.heartbeat_at,
                      },
                      null,
                      2
                    )}
                  </pre>
                </div>
              </div>
            </section>

            <section className="glass-panel p-5 rounded-xl">
              <h2 className="text-sm font-bold uppercase tracking-widest text-gray-400 mb-4 flex items-center gap-2">
                <FileText size={14} /> Files
              </h2>
              <ul className="text-xs font-mono space-y-1 mb-4">
                {snap.file_references.map((f) => (
                  <li key={f.path} className="text-gray-400">
                    <span className="text-gray-500">{f.label}:</span>{' '}
                    <code>{f.path}</code>
                  </li>
                ))}
              </ul>
              <details className="text-xs font-mono">
                <summary className="text-gray-500 cursor-pointer mb-2">
                  heartbeat.log tail
                </summary>
                <pre className="text-gray-300 bg-black/40 p-3 rounded overflow-x-auto whitespace-pre-wrap break-words max-h-40 overflow-y-auto">
                  {snap.heartbeat_log_tail || '(empty)'}
                </pre>
              </details>
              <details className="text-xs font-mono mt-2">
                <summary className="text-gray-500 cursor-pointer mb-2">
                  solis.log tail
                </summary>
                <pre className="text-gray-300 bg-black/40 p-3 rounded overflow-x-auto whitespace-pre-wrap break-words max-h-40 overflow-y-auto">
                  {snap.solis_log_tail || '(empty)'}
                </pre>
              </details>
              <details className="text-xs font-mono mt-2">
                <summary className="text-gray-500 cursor-pointer mb-2">
                  SOUL.md head
                </summary>
                <pre className="text-gray-300 bg-black/40 p-3 rounded overflow-x-auto whitespace-pre-wrap break-words max-h-40 overflow-y-auto">
                  {snap.soul_md_head || '(empty)'}
                </pre>
              </details>
            </section>
          </div>
        )}
      </div>
    </div>
  );
}
