/**
 * SolarpunkStructures.jsx
 * Lives in: frontend/src/biosphere/SolarpunkStructures.jsx
 *
 * Procedural Solarpunk architecture — all geometry generated by code.
 * Visual references: Vincent Callebaut's Asian Cairns, 3D-printed mycelium
 * by bioMATTERS, terracotta water catchers, Persian Badgir wind towers.
 *
 * Exports:
 *   WaterCatchmentTower  — terracotta spire, petals open on water proximity
 *   WindCatcher          — hexagonal Badgir tower, vanes rotate to wind
 *   LivingWall           — vine-covered wall segment with L-System growth
 *   BiosphereHearth      — the central Hearth Fire altar of the Farm
 */

import { useRef, useMemo } from 'react'
import { useFrame } from '@react-three/fiber'
import { Float, Text } from '@react-three/drei'
import * as THREE from 'three'

// ── Hearthlands palette ───────────────────────────────────────────
const C = {
  terracotta:  '#C27C5A',
  terracotta2: '#A05A3A',
  sand:        '#F5E6C8',
  sage:        '#7A9E7E',
  ember:       '#E8842A',
  deep:        '#3D2B1A',
  water:       '#4A90D9',
  aether:      '#AA88FF',
  gold:        '#D4A853',
  vine:        '#4A6A2A',
}

// ── Water Catchment Tower ─────────────────────────────────────────
// Terracotta spire that opens petals when water is nearby.
// Shape: tapered lathe profile, 6-sided, petal leaves at top.

export function WaterCatchmentTower({
  position = [0, 0, 0],
  scale    = 1,
  waterNearby = false,
  heat    = 0,
}) {
  const petalsRef = useRef()
  const dripsRef  = useRef([])

  // Petal open/close based on water proximity
  useFrame(({ clock }) => {
    if (!petalsRef.current) return
    const target = waterNearby ? 0.4 : 0.0
    const current = petalsRef.current.rotation.x
    petalsRef.current.rotation.x += (target - current) * 0.03
    petalsRef.current.rotation.y = clock.elapsedTime * 0.15
  })

  // Tower profile points for lathe geometry
  const profile = useMemo(() => {
    const pts = []
    // Base: wide → taper to mid → flare slightly → taper to tip
    const curve = [
      [0.0, 0.0],   // ground center
      [0.28, 0.0],  // base outer
      [0.30, 0.05],
      [0.22, 0.4],
      [0.15, 0.8],
      [0.12, 1.1],
      [0.14, 1.3],  // slight flare
      [0.10, 1.6],
      [0.06, 2.0],
      [0.02, 2.4],  // tip
    ]
    curve.forEach(([x, y]) => pts.push(new THREE.Vector2(x * scale, y * scale)))
    return pts
  }, [scale])

  return (
    <group position={position}>
      {/* Main tower body — lathe geometry */}
      <mesh castShadow receiveShadow>
        <latheGeometry args={[profile, 6]} />
        <meshStandardMaterial
          color={C.terracotta}
          roughness={0.85}
          metalness={0.05}
          side={THREE.DoubleSide}
        />
      </mesh>

      {/* Rim detail ring */}
      <mesh position={[0, 0.8 * scale, 0]}>
        <torusGeometry args={[0.22 * scale, 0.025 * scale, 6, 6]} />
        <meshStandardMaterial color={C.terracotta2} roughness={0.9} />
      </mesh>

      {/* Water basin at top */}
      <mesh position={[0, 2.0 * scale, 0]}>
        <cylinderGeometry args={[0.12 * scale, 0.08 * scale, 0.06 * scale, 6]} />
        <meshStandardMaterial
          color={waterNearby ? C.water : C.sand}
          roughness={0.3}
          metalness={waterNearby ? 0.4 : 0}
          emissive={waterNearby ? C.water : '#000'}
          emissiveIntensity={waterNearby ? 0.3 : 0}
        />
      </mesh>

      {/* Petals that open when water is near */}
      <group ref={petalsRef} position={[0, 1.9 * scale, 0]}>
        {Array.from({ length: 6 }).map((_, i) => {
          const a = (i / 6) * Math.PI * 2
          return (
            <mesh
              key={i}
              position={[Math.cos(a) * 0.18 * scale, 0, Math.sin(a) * 0.18 * scale]}
              rotation={[0, a, waterNearby ? -0.5 : 0]}
            >
              <ellipseGeometry args={[0.07 * scale, 0.14 * scale, 8]} />
              <meshStandardMaterial
                color={C.sage}
                roughness={0.7}
                side={THREE.DoubleSide}
                emissive={waterNearby ? C.water : '#000'}
                emissiveIntensity={waterNearby ? 0.2 : 0}
              />
            </mesh>
          )
        })}
      </group>

      {/* Water drip effect when full */}
      {waterNearby && (
        <pointLight
          position={[0, 1.5 * scale, 0]}
          color={C.water}
          intensity={0.4}
          distance={3}
        />
      )}
    </group>
  )
}

// ── Wind Catcher (Badgir) ─────────────────────────────────────────
// Persian wind tower, hexagonal, with rotating vanes.
// Opens to incoming wind direction, cools nearby water pools.

export function WindCatcher({
  position    = [0, 0, 0],
  scale       = 1,
  windAngle   = 0,    // radians, from IoT sensor eventually
  heat        = 1000,
}) {
  const vaneRef = useRef()

  useFrame(({ clock }) => {
    if (!vaneRef.current) return
    // Slowly orient to wind angle
    const target = windAngle
    const current = vaneRef.current.rotation.y
    vaneRef.current.rotation.y += (target - current) * 0.01

    // Gentle vane flutter
    vaneRef.current.children?.forEach((child, i) => {
      if (child.rotation) {
        child.rotation.z = Math.sin(clock.elapsedTime * 1.5 + i * 1.2) * 0.05
      }
    })
  })

  const cooling = Math.min(heat / 3000, 1)

  return (
    <group position={position}>
      {/* Tower shaft */}
      <mesh castShadow>
        <cylinderGeometry args={[0.12 * scale, 0.18 * scale, 2.0 * scale, 6]} />
        <meshStandardMaterial color={C.sand} roughness={0.85} />
      </mesh>

      {/* Top cap — hexagonal */}
      <mesh position={[0, 1.1 * scale, 0]}>
        <cylinderGeometry args={[0.22 * scale, 0.22 * scale, 0.08 * scale, 6]} />
        <meshStandardMaterial color={C.terracotta} roughness={0.8} />
      </mesh>

      {/* Wind vanes */}
      <group ref={vaneRef} position={[0, 0.9 * scale, 0]}>
        {Array.from({ length: 4 }).map((_, i) => {
          const a = (i / 4) * Math.PI * 2
          return (
            <mesh
              key={i}
              position={[Math.cos(a) * 0.2 * scale, 0, Math.sin(a) * 0.2 * scale]}
              rotation={[0, a + Math.PI / 2, 0]}
            >
              <boxGeometry args={[0.04 * scale, 0.35 * scale, 0.22 * scale]} />
              <meshStandardMaterial
                color={C.terracotta2}
                roughness={0.75}
              />
            </mesh>
          )
        })}
      </group>

      {/* Cool air emission when hot */}
      {heat > 2000 && (
        <pointLight
          position={[0, 0.5 * scale, 0]}
          color="#A0D8EF"
          intensity={0.3 * cooling}
          distance={4}
        />
      )}
    </group>
  )
}

// ── Living Wall ───────────────────────────────────────────────────
// Vine-covered wall segment. Grows taller as nearby flora blooms.

export function LivingWall({
  position   = [0, 0, 0],
  width      = 2,
  height     = 1.5,
  growthStage = 3,  // 0-6
}) {
  const vinesRef = useRef()

  useFrame(({ clock }) => {
    if (!vinesRef.current) return
    vinesRef.current.children.forEach((vine, i) => {
      vine.rotation.z = Math.sin(clock.elapsedTime * 0.8 + i * 0.7) * 0.04
    })
  })

  const vineCount = Math.floor(growthStage * 4)

  return (
    <group position={position}>
      {/* Wall structure */}
      <mesh receiveShadow castShadow>
        <boxGeometry args={[width, height, 0.15]} />
        <meshStandardMaterial color={C.sand} roughness={0.9} />
      </mesh>

      {/* Vines */}
      <group ref={vinesRef}>
        {Array.from({ length: vineCount }).map((_, i) => {
          const x = (Math.random() - 0.5) * width * 0.8
          const h = 0.3 + Math.random() * height * 0.7
          return (
            <mesh
              key={i}
              position={[x, -height / 2 + h / 2, 0.09]}
            >
              <boxGeometry args={[0.04, h, 0.03]} />
              <meshStandardMaterial color={C.vine} roughness={0.8} />
            </mesh>
          )
        })}
      </group>

      {/* Leaf clusters */}
      {growthStage >= 3 && Array.from({ length: Math.floor(vineCount / 2) }).map((_, i) => {
        const x = (Math.random() - 0.5) * width * 0.8
        const y = (Math.random() - 0.3) * height * 0.7
        return (
          <mesh key={i} position={[x, y, 0.1]}>
            <circleGeometry args={[0.08 + Math.random() * 0.08, 6]} />
            <meshStandardMaterial
              color={C.sage}
              roughness={0.7}
              side={THREE.DoubleSide}
            />
          </mesh>
        )
      })}
    </group>
  )
}

// ── Biosphere Hearth ──────────────────────────────────────────────
// The central altar of the Farm. The Hearth Fire burns here.
// This is where the $EMBER economy originates.

export function BiosphereHearth({
  position = [0, 0, 0],
  heat     = 2980,
  emberBalance = 2980,
}) {
  const flameRef = useRef()
  const glowRef  = useRef()

  const warmth = Math.min(heat / 5000, 1)

  useFrame(({ clock }) => {
    const t = clock.elapsedTime
    if (flameRef.current) {
      flameRef.current.scale.y = 0.8 + Math.sin(t * 4.2) * 0.3 * warmth
      flameRef.current.scale.x = 0.9 + Math.sin(t * 3.1 + 1) * 0.15
      flameRef.current.rotation.y = t * 0.5
    }
    if (glowRef.current) {
      glowRef.current.intensity = (0.8 + Math.sin(t * 2.5) * 0.3) * (0.3 + warmth * 0.7)
    }
  })

  return (
    <group position={position}>
      {/* Stone base ring */}
      <mesh receiveShadow>
        <cylinderGeometry args={[0.7, 0.85, 0.2, 8]} />
        <meshStandardMaterial color={C.deep} roughness={0.95} />
      </mesh>

      {/* Inner fire bowl */}
      <mesh position={[0, 0.15, 0]}>
        <cylinderGeometry args={[0.45, 0.55, 0.12, 8]} />
        <meshStandardMaterial color={C.terracotta2} roughness={0.8} metalness={0.1} />
      </mesh>

      {/* Ember coals */}
      <mesh position={[0, 0.22, 0]}>
        <cylinderGeometry args={[0.3, 0.3, 0.06, 8]} />
        <meshStandardMaterial
          color={C.ember}
          emissive={C.ember}
          emissiveIntensity={1.5 + warmth}
        />
      </mesh>

      {/* Flame cone */}
      <mesh ref={flameRef} position={[0, 0.45, 0]}>
        <coneGeometry args={[0.18, 0.5, 8]} />
        <meshStandardMaterial
          color="#FFD080"
          emissive="#FF8800"
          emissiveIntensity={2 + warmth * 2}
          transparent
          opacity={0.8}
        />
      </mesh>

      {/* Flame glow light */}
      <pointLight
        ref={glowRef}
        position={[0, 0.6, 0]}
        color={C.ember}
        intensity={1.5}
        distance={8}
        castShadow
      />

      {/* Stone pillars around hearth */}
      {Array.from({ length: 6 }).map((_, i) => {
        const a = (i / 6) * Math.PI * 2
        return (
          <mesh
            key={i}
            position={[Math.cos(a) * 0.65, 0.3, Math.sin(a) * 0.65]}
            castShadow
          >
            <boxGeometry args={[0.08, 0.6, 0.08]} />
            <meshStandardMaterial color={C.deep} roughness={0.9} />
          </mesh>
        )
      })}

      {/* $EMBER label */}
      <Float speed={1.5} floatIntensity={0.1}>
        <Text
          position={[0, 1.2, 0]}
          fontSize={0.18}
          color={C.gold}
          anchorX="center"
          anchorY="middle"
        >
          ⬡ {emberBalance?.toLocaleString() ?? '0'} $EMBER
        </Text>
      </Float>
    </group>
  )
}
